{% set name = "pyright" %}
{% set version = "0.0.12" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyright-{{ version }}.tar.gz
  sha256: a80003bc10e6400ee235b77bf30f87cb442611e8bd6f496fe4afd4ee44cda580

build:
  number: 0
  entry_points:
    - pyright=pyright.cli:entrypoint
    - pyright-python=pyright.cli:entrypoint
    - pyright-langserver=pyright.langserver:entrypoint
    - pyright-python-langserver=pyright.langserver:entrypoint
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<36]

requirements:
  build:
    - {{ compiler('c') }}
    - sysroot_linux-64 2.17  # [linux64]
  host:
    - pip
    - python
  run:
    - nodeenv >=1.6.0
    - python
    - typing_extensions >=3.7  # [py<38]

test:
  imports:
    - pyright
  commands:
    - pip check
    - pyright --help
    - pyright-python --help
    - pyright-langserver --help
    - pyright-python-langserver --help
  requires:
    - pip

about:
  home: https://github.com/RobertCraigie/pyright-python
  summary: Command line wrapper for pyright, a static type checker
  dev_url: https://github.com/RobertCraigie/pyright-python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
